<p>Yet An Otter Magic Inventory (yaomi) est un site web de gestion d'inventaire de cartes <span class="mtg">Magic</span>. Il vous permet de gérer votre collection de cartes en listant les cartes existantes et les extensions dans lesquelles elles apparaissent, ainsi que le nombre que vous possédez de chacune.</p>
<p>yaomi est multi-utilisateur et installable sur votre propre serveur. Configuration requise : </p>
<ul class="classic">
	<li>PHP version 5.1.6 ou plus</li>
	<li>une base de données MySQL 4.1 ou plus</li>
	<li>Apache : mod_rewrite (optionnel mais conseillé)</li>
	<li>Au 1<sup>er</sup> août 2013, à peu près 2 Go d'espace disque pour les images si vous décidez de les héberger chez vous. Attention, l'espace nécessaire augmentera avec le temps et les nouvelles cartes. Vous pouvez configurer yaomi pour aller chercher ces images sur mon serveur à cette adresse : <a href="http://sanctuaire.lamecarlate.net/media/images/Magic/pics">http://sanctuaire.lamecarlate.net/media/images/Magic/pics</a>. C'est un service que je propose (gratuitement s'entend), veuillez ne pas en abuser : si vous <em>pouvez</em> prendre ces images chez vous, <em>faites-le</em>, merci.</li>
</ul>
<p>Wizards publie régulièrement (tous les 3 mois environ) de nouvelles cartes. Je ferai de mon mieux pour proposer le plus rapidement des mises à jour de la base de données, mais ne vous attendez pas à les avoir le lendemain de la release.</p>
<p>Pourquoi &laquo;&thinsp;Yet An Otter Magic Inventory&thinsp;&raquo; ? Déjà, parce que ça faisait un jeu de mot pourri, et que je suis très forte à ça. Ensuite, à cause du manque flagrant de loutres dans l'univers de <span class="mtg">Magic</span>. Bon, d'accord, et de pandas roux. Et de phoques (non, les <a href="<?php echo site_url('card/search/selkie') ; ?>">trois selkies</a> ne comptent pas vraiment comme des phoques). Et de flamands roses mais c'est déjà moins mon truc. Et puis, effet de bord sympa, &laquo;&thinsp;yaomi&thinsp;&raquo; c'est très prononçable.</p>